# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsumBounded <- function(x, low, high) {
    .Call('_SBR_cumsumBounded', PACKAGE = 'SBR', x, low, high)
}

etcadj <- function(n, e, irrig, taw, p, k) {
    .Call('_SBR_etcadj', PACKAGE = 'SBR', n, e, irrig, taw, p, k)
}

ks <- function(n, e, irrig, taw, p, k) {
    .Call('_SBR_ks', PACKAGE = 'SBR', n, e, irrig, taw, p, k)
}

waste_water_adj <- function(n, e, irrig, taw, p, k) {
    .Call('_SBR_waste_water_adj', PACKAGE = 'SBR', n, e, irrig, taw, p, k)
}

wbadj <- function(n, e, irrig, taw, p, k) {
    .Call('_SBR_wbadj', PACKAGE = 'SBR', n, e, irrig, taw, p, k)
}

