# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsumBounded <- function(x, low, high) {
    .Call('_SBR_cumsumBounded', PACKAGE = 'SBR', x, low, high)
}

